### ISSUE TITLE
Optimize the analyze function.

### ISSUE THREAD

**Issue by AnchyDev** [AnchyDev/StatBooster#1]
The stat analysis function needs to be optimized and smarter. There are still some cases where items are incorrectly assigned stats that do not match the item.

**Comment by yuanf225** [comment]
I found your random enchantment mod more interesting

**Comment by AnchyDev** [comment]
> I found your random enchantment mod more interesting

I'm unsure of what you mean?

**Comment by AnchyDev** [comment]
Kind of falls under #9
