### ISSUE TITLE
Question about stats.

### ISSUE THREAD

**Issue by Parkan1986** [AnchyDev/StatBooster#16]
Does this module can use any stats id from Randomproperty.dbc or also Randomsuffix.dbc?

I ask this because theiy differs and stats from randomsuffix.dbc can be scale with item level if two different items will have same suffix but with different item level those stats will be differ.

**Comment by AnchyDev** [comment]
You must use enchant ids, as I am not utilizing the property/suffix system.
You can find information about it here: https://github.com/AnchyDev/StatBooster/wiki/Enchant%20Template

**Comment by Parkan1986** [comment]
Thank you for answer.Will test your module.Looks great
