### ISSUE TITLE
crash servera

### ISSUE THREAD

**Issue by MegaserverRU** [AnchyDev/StatBooster#18]
I can't figure out how to solve this problem the server crashes

[crash.zip](https://github.com/AnchyDev/StatBooster/files/10457475/crash.zip)

**Comment by heyitsbench** [comment]
[Gist](https://gist.github.com/heyitsbench/dc20800afdacb65e7ac0b93be23dfdc1).

**Comment by AnchyDev** [comment]
I'm surprised I have not hit that crash before. It should be fixed now.
