### ISSUE TITLE
Add more fields for the scoring table.

### ISSUE THREAD

**Issue by AnchyDev** [AnchyDev/StatBooster#20]
It might be a good idea to add extra scoring for the scoring field so the scores can be very specific.

For example, a cloth helmet with intellect would be scored as SPELL but a plate helmet with intellect would be scored also with SPELL where it should be HYBRID, adding extra fields would allow the user to score them differently.

**Comment by Glucius-TM** [comment]
It would be great to add the possibility of a more powerful enchantment, so along with the re-roll item it complements perfectly.

**Comment by AnchyDev** [comment]
This was solved a long time ago.
