### ISSUE TITLE
Some Enchants broke interface addons which show buffs durations.

### ISSUE THREAD

**Issue by Parkan1986** [AnchyDev/StatBooster#21]
After some testing and playing with this module i got weird situations with some interface addons.I am using NUI+ addon for wow https://www.curseforge.com/wow/addons/nui
After some time when i got item and equipeed it(example shield with enchant +5 health my interface start bugging and fps start slowdown because of errors.Buggrabber saved situation but it start spamming evry 30 sec to chat about bugs and NUi addon stopped showing buffs durations.I even tried few other addons which work with showing buffs, but they also was broken(example elks buffs https://www.curseforge.com/wow/addons/elkbuffbars )

**Comment by AnchyDev** [comment]
That is not something I can fix and would have to be fixed in the Addons. They are not correctly handling the enchant slots.
