### ISSUE TITLE
IlvlMin and ilvlMax not working

### ISSUE THREAD

**Issue by Glucius-TM** [AnchyDev/StatBooster#24]
I have added about 1k of enchants to test and the ilvl does not quite work well or does not work.

**Comment by AnchyDev** [comment]
can you show me examples of your enchant template? I have not had this issue occur

**Comment by Glucius-TM** [comment]
[Nuevo documento de texto.txt](https://github.com/AnchyDev/StatBooster/files/11554753/Nuevo.documento.de.texto.txt)

The racemask values ​​are not correct, but even so, it should apply the level restrictions, right?

**Comment by AnchyDev** [comment]
Those look correct to me, when the mask is 0 it should apply to all item types.

**Comment by Glucius-TM** [comment]
so are all enchants under item lvl working for you? I have added 3 more enchants to verify the faster process. maybe the problem could be here. In my case I have set fixed slots using PROP_ENCHANTMENT_SLOT_0 from 1 to 4 (only some green objects with random stats are affected) resulting in being able to enchant the entire gear without overwriting enchants. If you don't mind, I'll put the only fragment I've developed to test quickly.



if (itemClass)
{
    auto enchant1 = enchant;
    auto enchant2 = enchant;
    auto enchant3 = enchant;

    while (enchant1 && (enchant1 == enchant || enchant1 == enchant2 || enchant1 == enchant3))
    {
        enchant1 = sBoostConfigMgr->EnchantPool.Get(statType, itemClassMask, itemSubClassMask, itemTypeMask, itemLevel);
    }

    while (enchant2 && (enchant2 == enchant || enchant2 == enchant1 || enchant2 == enchant3))
    {
        enchant2 = sBoostConfigMgr->EnchantPool.Get(statType, itemClassMask, itemSubClassMask, itemTypeMask, itemLevel);
    }

    while (enchant3 && (enchant3 == enchant || enchant3 == enchant1 || enchant3 == enchant2))
    {
        enchant3 = sBoostConfigMgr->EnchantPool.Get(statType, itemClassMask, itemSubClassMask, itemTypeMask, itemLevel);
    }

    bool enchantmentApplied = EnchantItem(player, item, PROP_ENCHANTMENT_SLOT_0, enchant->Id, sBoostConfigMgr->OverwriteEnchantEnable) &&
        EnchantItem(player, item, PRISMATIC_ENCHANTMENT_SLOT, StatBoostMgr::ENCHANT_DUMMY, sBoostConfigMgr->OverwriteEnchantEnable);

    if (enchantmentApplied)
    {
        enchantmentApplied = EnchantItem(player, item, PROP_ENCHANTMENT_SLOT_1, enchant1 ? enchant1->Id : 0, sBoostConfigMgr->OverwriteEnchantEnable) &&
            EnchantItem(player, item, PRISMATIC_ENCHANTMENT_SLOT, StatBoostMgr::ENCHANT_DUMMY, sBoostConfigMgr->OverwriteEnchantEnable);
    }

    if (enchantmentApplied)
    {
        enchantmentApplied = EnchantItem(player, item, PROP_ENCHANTMENT_SLOT_2, enchant2 ? enchant2->Id : 0, sBoostConfigMgr->OverwriteEnchantEnable) &&
            EnchantItem(player, item, PRISMATIC_ENCHANTMENT_SLOT, StatBoostMgr::ENCHANT_DUMMY, sBoostConfigMgr->OverwriteEnchantEnable);
    }

    if (enchantmentApplied)
    {
        enchantmentApplied = EnchantItem(player, item, PROP_ENCHANTMENT_SLOT_3, enchant3 ? enchant3->Id : 0, sBoostConfigMgr->OverwriteEnchantEnable) &&
            EnchantItem(player, item, PRISMATIC_ENCHANTMENT_SLOT, StatBoostMgr::ENCHANT_DUMMY, sBoostConfigMgr->OverwriteEnchantEnable);
    }

    // Devolver si se aplicaron los encantamientos
    return enchantmentApplied;
}
return false;
}

**Comment by AnchyDev** [comment]
So the issue actually lies with the enchantment slots you have used.

```
    PROP_ENCHANTMENT_SLOT_0         = 7,                    // used with RandomSuffix and RandomProperty
    PROP_ENCHANTMENT_SLOT_1         = 8,                    // used with RandomSuffix and RandomProperty
    PROP_ENCHANTMENT_SLOT_2         = 9,                    // used with RandomSuffix and RandomProperty
    PROP_ENCHANTMENT_SLOT_3         = 10,                   // used with RandomSuffix and RandomProperty
    PROP_ENCHANTMENT_SLOT_4         = 11,                   // used with RandomSuffix and RandomProperty
```
These slots are reserved for Random suffixes like `of the Whale`. The client will not show these unless the item has a Random Property Id attached to the item. The stats will also show incorrect as far as I know.

These are the reasons I only developed the module with one slot:
- To not make enchanting redundant.
- Issues with other slots not displaying correctly.

I hope that answers your issue.

**Comment by Glucius-TM** [comment]
Thank you very much for the information, I will continue testing
