### ISSUE TITLE
Hotlinked items do not show as enchanted.

### ISSUE THREAD

**Issue by StraysFromPath** [AnchyDev/StatBooster#25]
On sheet: 
![image](https://github.com/AnchyDev/StatBooster/assets/119371540/9686cc7c-4ae5-4b93-86ed-68e1ddae9db7)

When linked to chat:
![image](https://github.com/AnchyDev/StatBooster/assets/119371540/462f83e6-67ca-4b48-bee4-ab022a55383b)

It would be nice if enchants were visible so that they can be seen via linking.

E.g. uses:

"WTS: [link]"

or

"/w hey friend look at [link] how cool is this"

**Comment by AnchyDev** [comment]
The reason they don't show as enchanted is because the client does not store the information for these enchants inside the permalinks. This is unfortunately not solvable without patching the client.
