### ISSUE TITLE
[Feature Request] Reroll/Add Statbooster Enchantment NPC/Item(?)

### ISSUE THREAD

**Issue by StraysFromPath** [AnchyDev/StatBooster#28]
Hi Anchy,

LOVING this module a necessary part of my group's server.

The most requested feature is a way to reroll the random enchantment or add a random enchantment to an item which has been suggsted in a few ways:

This is big for things like if you craft a Thunderfury and it doesn't get a random enchant you can feel super unlucky and are you really gonna go do all that again?

Or the Tier 0.5 dungeon set quests that can only be done once.

A) An NPC you can talk to that will roll a random enchant onto an item for a price (e.g 1g per ilvl).

B) An inscription recipe/item that can be used to reroll an item's random enchant.

**Comment by AnchyDev** [comment]
> Hi Anchy,
> 
> LOVING this module a necessary part of my group's server.
> 
> The most requested feature is a way to reroll the random enchantment or add a random enchantment to an item which has been suggsted in a few ways:
> 
> This is big for things like if you craft a Thunderfury and it doesn't get a random enchant you can feel super unlucky and are you really gonna go do all that again?
> 
> Or the Tier 0.5 dungeon set quests that can only be done once.
> 
> A) An NPC you can talk to that will roll a random enchant onto an item for a price (e.g 1g per ilvl).
> 
> B) An inscription recipe/item that can be used to reroll an item's random enchant.

https://github.com/AnchyDev/StatBoosterReroller/tree/master

Why I made this a separate repo is beyond me

**Comment by AnchyDev** [comment]
Add that module then setup a way to get item id 41605

**Comment by StraysFromPath** [comment]
OMG HUGE THANK YOU

Would it be possible to incorporate the reroller into this repo?

**Comment by AnchyDev** [comment]
It's unlikely right now as I am working on other things.

**Comment by AnchyDev** [comment]
> OMG HUGE THANK YOU
> 
> Would it be possible to incorporate the reroller into this repo?

I ended up merging it in anyway, you don't need the additional module anymore.
